"""empty message

Revision ID: 02f2c5bd5f3e
Revises: ebec3c116b3c
Create Date: 2022-11-16 10:28:29.364057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f2c5bd5f3e'
down_revision = 'ebec3c116b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('master', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'master')
    # ### end Alembic commands ###
