"""empty message

Revision ID: b5333a309026
Revises: 69bc0489308c
Create Date: 2022-11-16 20:52:38.304449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5333a309026'
down_revision = '69bc0489308c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car', sa.Integer(), nullable=True),
    sa.Column('truck', sa.Integer(), nullable=True),
    sa.Column('helicopter', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
